name: "XCTesting"
description: "A GitHub Action that runs `xcodebuild test`"
branding:
  icon: "code"
  color: "orange"

inputs:
  working-directory:
    description: "Directory to run `xcodebuild test` in"
    required: false
    default: "."
  schema:
    description: "The schema you want to run tests for"
    required: true
  destination:
    description: "String arguments for the `destination` flag"
    required: true

outputs:
  exit-code:
    value: ${{ steps.run-tests.outputs.exit-code }}
    description: "The exit code from the Swift test run"

runs:
  using: "composite"
  steps:
    - name: Run Tests
      id: run-tests
      shell: bash
      run: |
        xcodebuild test \
          -scheme '${{ inputs.schema }}' \
          -destination '${{ inputs.destination }}'