name: 'SwiftLint'
description: 'A GitHub Action that runs SwiftLint with custom and default rules'
branding:
  icon: 'code'
  color: 'orange'

runs:
  using: 'composite'
  steps:
    - name: Install SwiftLint
      shell: bash
      run: |
        brew install swiftlint
    - name: Run SwiftLint
      shell: bash
      run: |
        cd ${{ inputs.working-directory }}
        swiftlint lint --reporter github-actions-logging

inputs:
  working-directory:
    description: 'Directory to run SwiftLint in'
    required: false
    default: '.'

outputs:
  exit-code:
    description: 'The exit code from the SwiftLint run'