name: 'SwiftLint'
description: 'A GitHub Action that runs SwiftLint with custom and default rules'
branding:
  icon: 'code'
  color: 'orange'

inputs:
  extra_args:
    description: "Extra arguments to override default lint config"
    required: false
    default: ""
  working-directory:
    description: 'Directory to run SwiftLint in'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Init Submodules
      shell: bash
      run: |
        git submodule init
        git submodule update --recursive --depth 1

    - name: Install Node.js LTS
      shell: bash
      run: |
        set -euo pipefail

        VERSION="v22.14.0"
        ARCH="linux-x64"
        URL="https://nodejs.org/dist/${VERSION}/node-${VERSION}-${ARCH}.tar.xz"

        curl -fsSL "$URL" -o node.tar.xz
        tar -xf node.tar.xz
        mv "node-${VERSION}-${ARCH}" /tmp/node

        echo "/tmp/node/bin" >> $GITHUB_PATH
    - name: Install SwiftLint
      shell: bash
      run: |
        curl -L https://github.com/realm/SwiftLint/releases/latest/download/swiftlint_linux.zip -o swiftlint.zip
        unzip -n swiftlint.zip
        chmod +x swiftlint
        sudo mv swiftlint /tmp/swiftlint
    - name: Run SwiftLint
      shell: bash
      run: |
        cd ${{ github.action_path}} ; npm run config
        cd ../
        CONFIG_ARG="--config ${{ github.action_path }}/.swiftlint.yml"
        if [[ -n "${{ inputs.working-directory }}" ]]; then
          cd ${{ inputs.working-directory }}
        fi
        ls
        /tmp/swiftlint lint $CONFIG_ARG ${{ inputs.extra_args }}

outputs:
  exit-code:
    description: 'The exit code from the SwiftLint run'
